### ISSUE TITLE
[DOC] Explain how event handling works on island components

### ISSUE THREAD

**Issue by lukemelia** [mitchlloyd/ember-islands#1]
Does event delegation work? What is the `parentView` of the island-rendered components?

Mostly curious how robust of a solution this addon is.

**Comment by mitchlloyd** [comment]
@lukemelia I suspect that Ember is still taking ownership of the body tag on the page. It gets the class "ember-application".

I expanded the dummy app in the test folder of this project to include a component nested in another. You can see that click events on buttons are working.

The `parentView` of a top level component is `undefined`. Obviously you can't access elements outside of a top level component with methods like `nearestOfType`, but I haven't been able to identify any issues with this technique yet. I've used this approach on one project to render a handful of widgets.

If you have some time I it would be cool if you could poke around with the dummy app in the test directory and see where this approach falls down. I'm also curious about what, if any, impact the recent component re-rendering work that Tom and Yehuda are doing will have.

**Comment by lukemelia** [comment]
@mitchlloyd I don't have time to review before Ember Conf, but you should keep in mind that Ember attaches event delegation at an app's `rootElement`. This defaults to `body` as you were describing, but can be overridden to be another element. This may be worth noting in your docs.

**Comment by mitchlloyd** [comment]
Fixed by 986e6b37067f8069e2d7f43440cca257d9788883. I look forward to seeing your talk at EmberConf.

**Comment by lukemelia** [comment]
:+1: See you in Portland!
