### ISSUE TITLE
Introduction to ember-islands lightning talk at a future Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [mitchlloyd/ember-islands#11]
Would you be open to giving an Introduction to `ember-islands` talk about a future Global Ember Meetup?

The talk is usually 15 minutes long and answers the following questions:

1. What problem is the addon trying to solve?
2. How to get started?
3. How should it be used?
4. What should person be aware of?

We'll produce a video that you can link to in your README. You can see existing videos here https://vimeo.com/album/3607049

What do you think?

**Comment by mitchlloyd** [comment]
Hey Taras,

Not sure if you remember but we met very briefly at a breakfast spot at
last EmberConf. I really like what you've been doing with the Global Meetup.

Yes! I would like to give a talk. Those questions are a good start, and
there is actually some pretty interesting stuff with the Ember public
`visit` API (probably coming in 2.3) that will make the next version of
this addon much simpler and allow for some interesting new features.

I looked around for the next date, but didn't see anything right away. Let
me know the date/time and any other logistics.

**Comment by taras** [comment]
That’s awesome and thank you for the kind world. The community’s openness to contributing is what makes it awesome.

I hear you about Ember 2.3 visit API. Would you prefer to hold off the recoding until then?

-- 
Taras Mankovski

On October 13, 2015 at 12:13:55 PM, Mitch Lloyd (notifications@github.com) wrote:

Hey Taras,

Not sure if you remember but we met very briefly at a breakfast spot at
last EmberConf. I really like what you've been doing with the Global Meetup.

Yes! I would like to give a talk. Those questions are a good start, and
there is actually some pretty interesting stuff with the Ember public
`visit` API (probably coming in 2.3) that will make the next version of
this addon much simpler and allow for some interesting new features.

I looked around for the next date, but didn't see anything right away. Let
me know the date/time and any other logistics.

**Comment by mitchlloyd** [comment]
@taras I've got the next version of Ember Islands finalized (as far as I know right now). I'll be waiting on the Ember 2.3 release for 1.0 so any time near the end of December or later would work great. Could you fit me in around that time?

**Comment by taras** [comment]
I'm thinking sometime in January. What do you think?

**Comment by mitchlloyd** [comment]
That would be great.

**Comment by taras** [comment]
@mitchlloyd how does January 16th or January 30th sound?

**Comment by mitchlloyd** [comment]
16th would probably be a little better, but both would work.

**Comment by taras** [comment]
16th it is :) Consider it booked. Look forward to it!
