### ISSUE TITLE
Interim 0.5.5 release

### ISSUE THREAD

**Issue by praxxis** [mitchlloyd/ember-islands#16]
I know we're pushing for 1.0 but would you be able to push up a 0.5.5 release @mitchlloyd.

**Comment by mitchlloyd** [comment]
So the commit history is a little botched, but the 0.5.4 version should be up-to-date with current master.

**Comment by mitchlloyd** [comment]
I'm realizing that it's probably better to release a version 0.5.5 and yank 0.5.4 since the commit history is so confusing.
