### ISSUE TITLE
[DOC] Document how to call ember model

### ISSUE THREAD

**Issue by gandalfar** [mitchlloyd/ember-islands#17]
README form next-version already makes it much easier to get started with the project. I would suggest adding a section with example how to call model from the component. Something like:

## Models

To access your model from the component, you can inject `store` into the component.

```javascript
//component.js
import Ember from 'ember';
export default Ember.Component.extend({
  store: Ember.inject.service('store'),
  setupFlags: function(){
    this.document = this.get('store').findRecord('document', this.document_id);
  }.on("init")
});
```

```html
<div data-component='document-view' data-attrs='{"document_id": 123}'>
   <p>Some optional innerContent</p>
</div>
```

**Comment by mitchlloyd** [comment]
@gandalfar I'm glad the new readme is an improvement! I'm already a little concerned about the length of the readme so I'm wary of adding a section specifically for this. It might make more sense to expand the current usage example to show using the Ember data store. I've got at least one more iteration to do on the readme to update the recommended "default" approach so I'll keep this in mind.
