### ISSUE TITLE
Migration guide for moving from islands 0.5.* to 1.*? 

### ISSUE THREAD

**Issue by alexmiddeleer** [mitchlloyd/ember-islands#27]
It would be pretty sweet if you distilled a bit of the conversation from https://github.com/mitchlloyd/ember-islands/issues/14 into version 1's README file. I'm currently upgrading our islands setup, and as a programmer new to ember it has been a bit tricky so far :) 

I will give it a shot and if I am successful and think there is a straightforward "upgrade path", I'll post notes here or make a pull request.

**Comment by mitchlloyd** [comment]
Sure! I think the trickiest thing is migrating from a world where you didn't need to render a route at all (pre 1.x) to a world where rendering a template is the entry point to begin rendering island components. In other words, 1.x will render your application template and application route whereas 0.x did not. 

Honestly, this can be a non-trivial hump to get over in an application that has a lot of setup in the application route, controller, and template. The bottom line is that there are public APIs to prevent this rendering in Ember.

I'm keeping my eyes on all the Fastboot and Engines APIs as they make their way into Ember. My hope is that the boot process will continue to become more flexible and open up public APIs that would allow Ember Islands to boot an application with an Event Dispatcher that does not load the application template.

**Comment by mitchlloyd** [comment]
I would be interested in feedback about the 0.5 to 1.0 upgrade path if you have any. For now I'll close this issue but let me know if there's anything you found that may be useful for other users.
