### ISSUE TITLE
Possible to use without removing application.hbs

### ISSUE THREAD

**Issue by himynameisjonas** [mitchlloyd/ember-islands#3]
Is it possible to use the ember app as a whole app (with the application.hbs) and at the same time use it with ember-island on other parts on our website? We have started implementing some new parts of our website as a ember app (with ember-cli-rails) but want to share some new components with the old rails app views.

**Comment by mitchlloyd** [comment]
That sounds like a cool use case. I just looked around for a little trying to find a good way to do this. Could you tell me what version of Ember you're using? It looks like newer versions might have more options to accomplish this.

Something that will work across all 1.x versions is overriding your Application route so that it renders nothing:

```javascript
// In application.js
export default Ember.Route({
  renderTemplate: function() {
    if (window.DONTRENDERAPPLIATIONTEMPLATE) {
      return;
    } else {
      this._super();
    }
  }
});
```

However that is a little sad. Let me know what version of Ember you're using and I'd like to take some time to look around for a better solution.

**Comment by acorncom** [comment]
I'd love to hear the outcome of this as well, as I can see clear use cases for this coming up for my clients in the future.  Nothing on the horizon yet, but it'd be awesome to know how :-)

**Comment by himynameisjonas** [comment]
I'm using `1.10.0` :)

**Comment by mitchlloyd** [comment]
@acorncom For Canary versions of Ember today with FastBoot (TM) integration, there is an option to set `{ autoboot: false }` for your app to prevent the initial render. This seems like a good option for your future clients. 

For now I'll continue to investigate ways this library can help.

**Comment by mitchlloyd** [comment]
@himynameisjonas I just pushed a branch that stops the Router from doing anything when the application boots:

https://github.com/mitchlloyd/ember-islands/tree/cancel-routing

This means that you no longer need to remove your application.hbs file. 

I'm assuming that you would want to have some configuration to turn ember-islands on and off. You would want it "on" in your legacy Rails application, but off when running the application normally. Is that correct?

If that's the case I'm thinking of adding some config that you could set in your config/environment.js file. Something like `USE_EMBER_ISLANDS: false`. Then in your legacy Rails app you could set the `window.EmberENV` to `{ USER_EMBER_ISLANDS: true }`. Would something like that work?

**Comment by himynameisjonas** [comment]
Yeah, your assumptions are correct. the `window.EmberENV = { USER_EMBER_ISLANDS: true }` sounds like a really nice way of controlling this. Awesome! :)

**Comment by mitchlloyd** [comment]
Closing in favor of PR #4.
