### ISSUE TITLE
Need More Documentation for an Ember Newbie

### ISSUE THREAD

**Issue by RALifeCoach** [mitchlloyd/ember-islands#31]
Your documentation assumes some Ember knowledge. For someone coming to Ember from a legacy code base, that may be a false assumption. (In my case it is certainly a false assumption.) Can you create a step by step example for a newbie?

**Comment by locks** [comment]
Hi @RALifeCoach, would you be willing to go on the Ember Slack group to discuss this? Given that this is an Ember addon, I'm not sure how the documentation would address that, or how much return that investment would bring.
Have you given the [offical Guides](https://guides.emberjs.com/) a run-through? We offer a tutorial that might help you get started.

**Comment by RALifeCoach** [comment]
If my company was willing to pay you, are you available? How much would you
want to get me up and running?

**Comment by mitchlloyd** [comment]
I agree with @RALifeCoach that the README could point new Ember developers in the right direction given that this addon might the first point of contact for a new Ember developer. However, as @locks pointed out, the best information for getting started with Ember is the Guides so I don't want to duplicate (and then maintain) that information here. 

I'll add a sentence or linking to the [Ember Guides quick start](https://guides.emberjs.com/v2.8.0/getting-started/quick-start/) and take the rest of this conversation offline.
