### ISSUE TITLE
Ember.assert not available in production

### ISSUE THREAD

**Issue by patric-eberle** [mitchlloyd/ember-islands#36]
In our project, we're using Ember with ember-islands to partially show content on a pre-rendered page. The island divs are delivered by the pre-render engine as well. We had the issue, that the `data-component` attribute sometimes contained an invalid or not yet implemented component name. This caused the following method to crash (on `component.create(attrs)`):

```
// ember-islands.js
function getRenderComponentFor(emberObject) {
  let owner = getOwner(emberObject);

  return function renderComponent({ name, attrs, element }) {
    let { component, layout } = lookupComponent(owner, name);
    assert(`ember-islands could not find a component named "${name}" in your Ember appliction.`, component);

    if (layout) {
      attrs.layout = layout;
    }

    $(element).empty();
    let componentInstance = component.create(attrs);
    componentInstance.appendTo(element);
    return componentInstance;
  };
}
```

I think this is caused, because according to the Ember API assert is only available in non-production builds (http://emberjs.com/api/#method_assert). I think in this case it would be better, to also add an error handler, which would prevent code execution and give a console feedback, if the given component was not found.

**Comment by mitchlloyd** [comment]
Thanks for filing this issue.

I agree that it makes sense for Ember Islands to be as resilient as possible in a production environment, since it's often hard to keep the backend and frontend perfectly in sync.

Could you open a PR and show me what kind of error handling you are thinking of?

Perhaps we can use the fact that `Ember.assert` is a no-op in production mode and add a guard after the assert to return and log a warning.

**Comment by rwjblue** [comment]
Ember.assert is present in prod builds, the documentation is describing that in production it is a no op (e.g. It never actually throws).

**Comment by patric-eberle** [comment]
Any suggestions how to determine if Ember.assert() is NOP or active? I'm not sure if the current environment can be used because we don't know the setup of the project.

**Comment by rwjblue** [comment]
```
var IS_PRODUCTION = (function(){
  try {
    Ember.assert('test assertion');
    return true;
  } catch(e) {
    return false;
  }
})();
```

**Comment by rwjblue** [comment]
^ is just one way, though I agree that Ember should make this simpler...

**Comment by mitchlloyd** [comment]
In this particular case adding another guard after the `assert` should work. @patric-eberle I'm curious what you think the best behavior would be when we reach that guard.

```js
function getRenderComponentFor(emberObject) {
  let owner = getOwner(emberObject);

  return function renderComponent({ name, attrs, element }) {
    let { component, layout } = lookupComponent(owner, name);
    assert(`ember-islands could not find a component named "${name}" in your Ember application.`, component);

    // Will only reach in prod when there is no component.
    if(!component) {
      // console.warn? Render a default warning element on the page?
      return; 
    }

    if (layout) {
      attrs.layout = layout;
    }

    $(element).empty();
    let componentInstance = component.create(attrs);
    componentInstance.appendTo(element);
    return componentInstance;
  };
}
```

**Comment by patric-eberle** [comment]
@rwjblue Thank you for this smart solution. I guess this should work. But I'm with you: may it could be useful if assert would return true/false in production.

@mitchlloyd I guess you're right. If assert is active and throws an error, parser wouldn't even reach the second evaluation. I guess using a console.warn and a HTML output together would be the best solution. Users often don't take a look at the console when reporting errors, while the console could also give error about elements which are for example hidden by CSS.
