### ISSUE TITLE
JS execution stops if unknown component is called

### ISSUE THREAD

**Issue by jonasbuechel** [mitchlloyd/ember-islands#40]
**Use case**:

The backend programmer prepares a ember-island integration like this:

`<div data-component='user-profile' data-attrs='{...}'></div>`

but the builded JavaScript doesn't contain a component 'user-profile' yet.

**Error**:
JavaScript Execution stops

**Enhancement**
Would be a good idea to integrate an error handler for this case, which prevents the JS Execution stop.

**Comment by mitchlloyd** [comment]
@jonasbuechel I believe we attempted to solve this same problem with this PR: https://github.com/mitchlloyd/ember-islands/pull/37. Are you using version 1.2.0?

**Comment by mitchlloyd** [comment]
@jonasbuechel Let me know if this is still an issue with 1.2.0.
