### ISSUE TITLE
Shared nav between ember / non-ember, ember-ified nav links?

### ISSUE THREAD

**Issue by adambedford** [mitchlloyd/ember-islands#44]
I haven't made it this far implementing ember-islands so this is a pre-emptive question -

I assume that when rendering the ember app in a sub-container with a shared nav for ember / non-ember features, the nav links wouldn't be able to be "ember-ified" i.e. Clicking the link would cause a full page reload, and then load the ember app vs. transitioning to the route. Am I right in thinking this? Is there a good way to solve this or is it a non-issue because booting the app is lightning fast with ember islands?

**Comment by mitchlloyd** [comment]
Here are a couple of options that should work if you don't want a full page refresh when you click these links.

1. Make the links in the shared header Ember Islands components that use `link-to`.

The main issue you'll run into here is that the statically rendered stuff is going to appear before Ember boots. The most practical thing may be to put static link content inside of the placeholder `divs`. Ember Islands will clear the contents of these divs when it renders and replace them with Ember `link-to` components that you supply. 

2. You could make your own JavaScript-enabled links that find your Ember application global, get the `ApplicationInstance` from that, and then use (`lookup`) to find `router:main` and call `transitionTo`.

It seems like option 1 should work pretty well. Option 2 seems like a bit of work.

**Comment by adambedford** [comment]
Thank you, Mitch. That is helpful. Option 1 certainly seems like the way to go!

**Comment by mitchlloyd** [comment]
Cool. Closing for now, let me know if something doesn't work out.
