### ISSUE TITLE
Inside an existing single page app

### ISSUE THREAD

**Issue by bvoelker** [mitchlloyd/ember-islands#47]
We are looking at integrating parts of an ember app into a react app. Is that something you saw as possible?

**Comment by mitchlloyd** [comment]
This is definitely possible. Whether this is the right set of trade-offs for your situation is a complicated and difficult question. Seams between frameworks tend to be a big source of maintenance pain usually more as a result of dependency management than any technical issues stitching them together.

As to whether ember-islands can help with an approach like this: it _could_ by rendering placeholders in your React app and then using the new reconcile feature to update these components. However, you're probably going to have more success by investigating the core workings of this addon (looking up a component in the Ember container and then rendering it into a DOM element via the `appendTo` API).

All in all you'll be fighting an uphill battle by using private-ish APIs in Ember, attempting to keep integrated repos in sync, while adding the overhead of 2 frameworks for your users. This could make sense in the short-term, but will be pretty painful in the long-term.
