### ISSUE TITLE
Is it possible to emulate server-rendered island within an ember route?

### ISSUE THREAD

**Issue by erichonkanen** [mitchlloyd/ember-islands#49]
Hey so I just discovered this addon after working on a project with a very similar implementation and use case and I'm considering doing a spike on switching to use this. However one thing that I don't think will work currently (as I've tried locally using roughly the [same code](https://github.com/mitchlloyd/ember-islands/blob/master/addon/utils/get-render-component.js#L22) is if you try to emulate the server-rendered code snippets inside a template.

The use case is that we have an ember app that customers inject as little mini "components" within their own arbitrary websites. They can render the components they want by doing simple code snippets just like this library is built around e.g.:
```
<div
    data-component="login-form"
    data-auth-redirect-url="/week"
></div>
```

However it's become apparent that testing is a real problem for this application so I wanted to create a few conditional routes (based on environment) so that we can emulate a customer site from within our ember app itself thus easing development/testing.

I created `app/routes/login` (customers could have e.g. foo.com/login-page/) and inserted the code snippet above, however when the page loads it throws an assertion error that says `Assertion Failed: You cannot append to an existing Ember.View.`.

Now I know we could render the component directly there but then we wouldn't get all the `data-attrs` and the behavior wouldn't mirror a customer site as closely, so

Is this possible or do you have other ideas for it?

Thanks!

**Comment by mitchlloyd** [comment]
Ember [won't let you append components inside of an Ember view](https://github.com/emberjs/ember.js/blob/d0de6ae3a77ab5a5156e62d3be7543302caf8c0f/packages/ember-views/lib/mixins/view_support.js#L207). Seems like a reasonable assertion.

Just put some HTML somewhere on the page that's outside of your Ember app for testing. This repo has some [examples of this in the acceptance tests](https://github.com/mitchlloyd/ember-islands/blob/master/tests/acceptance/rendering-components-test.js#L11-L15). It's also possible to render static pages in ember-cli (take a look at `index.html` in your Ember CLI app for an example) and then render island components there.
