### ISSUE TITLE
router.js cannot have a route defined as '/' if setting locationType to 'none'

### ISSUE THREAD

**Issue by swgamerx** [mitchlloyd/ember-islands#50]
Posting here for future reference for other users. 

while setting `locationType: 'none'` into the environment.js file will allow you to use a component as an island on any url route, it will break if you have a route defined as root within router.js such as the following `this.route('home',{path: '/'});`.

**Comment by mitchlloyd** [comment]
@swgamerx Thanks for following up with this issue. Could you paste the actual error that you were getting?

I don't want to fill the docs with all the things that you _shouldn't do_ (especially if they are just general Ember gotchas), but I'm wondering if some adjustments to the documentation could help.

Current: 
> If you want to render island components on any server-rendered page you can add the {{ember-islands}} component to your application.hbs template file and configure the router locationType to ignore the URL.

To: 
> If you don't need to use routing in your Ember app and you only need to render island components on server-rendered pages, you can add the {{ember-islands}} component to your application.hbs template file and configure the router locationType to ignore the URL.

Do you think this change would have helped you avoid this problem? Is there some other part of the docs that you think could guide people away from this issue?
