### ISSUE TITLE
Reuse/cache ember app across wordpress pages

### ISSUE THREAD

**Issue by erichonkanen** [mitchlloyd/ember-islands#51]
When using a pattern like ember-islands, each time the user navigates to a different page on host site that loads some ember components into the server-rendered page, it also means rebooting the entire ember app. Would it be possible to somehow store the entire ember app locally and then use the stored version instead of reloading the whole app each time a user changes pages? just hypothetical

There is ember-service-worker that seems like you could maybe cache some of the data but not sure

**Comment by mitchlloyd** [comment]
My understanding of Service Workers is that they are a tool to intercept and cache network requests. The [Motivation](https://w3c.github.io/ServiceWorker/#motivations) part of the spec is a good summary. I'm not aware of a way this could avoid rebooting an Ember app between page loads.

To get to the experience you're looking for I would explore a "turbo links" style approach. By intercepting link clicks and replacing HTML on the page via an AJAX call, you would keep the Ember app in memory and improve the perceived performance of the whole page. Ember Islands is equipped to handle this case via the [`reconcile`](https://github.com/mitchlloyd/ember-islands#reconciling-ember-island-components-with-dom-changes) function. You would call this function after replacing the page HTML.
