### ISSUE TITLE
Only the last declared component is rendered in Ember 1.13-beta.1

### ISSUE THREAD

**Issue by praxxis** [mitchlloyd/ember-islands#7]
See https://github.com/praxxis/islands-test for a reproduction repo. 

```
    <div data-component="component-one"></div>
    <div data-component="component-two"></div>
```
renders thusly:

In 1.13:
![one](https://dl.dropboxusercontent.com/u/106084/screenshots/sU4W.png)

In 1.12 (working):
![two](https://dl.dropboxusercontent.com/u/106084/screenshots/NCkn.png)

**Comment by mitchlloyd** [comment]
It looks like I'm the only person on earth who has tried to use `view#replaceIn` because it's broken again. I'm just going to stick with `view#appendTo` because it's used everywhere in the Ember tests. Let me know if you agree that the latest master changes fix this issue.

**Comment by praxxis** [comment]
Works for me on master, cheers

**Comment by mitchlloyd** [comment]
Released version 0.5.1 with this fix.

**Comment by rohmann** [comment]
@mitchlloyd Not the most ideal, but I really needed to get rid of that wrapping div. Unwrapping it with jQuery did the trick.

https://github.com/mitchlloyd/ember-islands/blob/master/addon/components/ember-islands.js#L50

```
// Work around for #replaceIn bug
$(element).empty();
let componentInstance = component.create(attrs);
componentInstance.appendTo(element);
$(element).contents().unwrap();
return componentInstance;
```

**Comment by mitchlloyd** [comment]
@rohmann I always thought keeping the wrapping div around was nice, but maybe there is a need to remove it sometimes? Can you tell me about your use case?

Also keep in mind that if it is an issue with the `display: block` default of `div`s, then `span` or any tag will do.
