### ISSUE TITLE
Initalizer error in 2.0.0-canary+e6517064

### ISSUE THREAD

**Issue by praxxis** [mitchlloyd/ember-islands#8]
Trying to run Ember with ember-islands in canary is throwing the following error:
```
Uncaught Error: Assertion Failed: No application initializer named 'registerComponentLookup'
_emberMetalCore.default.assert	@	ember.debug.js:5320
(anonymous function)	@	ember.debug.js:4323
(anonymous function)	@	ember.debug.js:4348
visit	@	ember.debug.js:2238
visit	@	ember.debug.js:2236
DAG.topsort	@	ember.debug.js:2349
_emberRuntimeSystemNamespace.default.extend._runInitializer	@	ember.debug.js:4347
_emberRuntimeSystemNamespace.default.extend.runInitializers	@	ember.debug.js:4322
_emberRuntimeSystemNamespace.default.extend.boot	@	ember.debug.js:4239
_emberRuntimeSystemNamespace.default.extend.domReady	@	ember.debug.js:4225
Backburner.run	@	ember.debug.js:222
Backburner.join	@	ember.debug.js:261
run.join	@	ember.debug.js:19537
run.bind	@	ember.debug.js:19600
jQuery.Callbacks.fire	@	base.js:3124
jQuery.Callbacks.self.fireWith	@	base.js:3236
jQuery.extend.ready	@	base.js:3448
completed	@	base.js:3479
```

Seems to be related to `registerComponentLookup` changing from an `initializer` [in 1.13](https://github.com/emberjs/ember.js/blob/v1.13.0-beta.2/packages/ember-htmlbars/lib/system/bootstrap.js#L98) to an `instanceInitializer` [in canary](https://github.com/emberjs/ember.js/blob/4d97d612ebe0841c0d40e57b276c9bc2bf896768/packages/ember-htmlbars/lib/system/bootstrap.js#L98).

**Comment by praxxis** [comment]
Changed in Ember at https://github.com/emberjs/ember.js/commit/2a726161dd80b3cfd5172922106037bbcc3e4d68

**Comment by praxxis** [comment]
So simply switching to an `instance-initializer` doesn't work 100% as we no longer have the application instance to check for `EMBER_ISLANDS.bypass`.

**Comment by mitchlloyd** [comment]
Thanks for reporting and tracking down the issue with `registerComponentLookup`.

Just looking at the documentation for instance initializers it sounds like this is prefect for Ember Islands, which only used the application and not the registry. But you're saying that if we use an `instance-initializer` for `boot-ember-islands` we can't get access to the `EMBER_ISLANDS.bypass` flag?

Is there some way we could use 2 separate initializers as shown in the [deprecations guide](http://emberjs.com/deprecations/v1.x/#toc_access-to-instances-in-initializers)?

After that's figured out I have to see if there is someway to make it backwards compatible or if there needs to be a 2.0 only version of ember-islands :neutral_face:

**Comment by praxxis** [comment]
Ugh that commit went into 1.13 final. I'll make some time to look at this tomorrow.

**Comment by praxxis** [comment]
fixed in https://github.com/mitchlloyd/ember-islands/pull/9
